### ISSUE TITLE
Preview does not return og:image tag as image

### ISSUE THREAD

**Issue by haansplosion** [LeonardoCardoso/SwiftLinkPreview#109]
Parsing any Spotify link: https://open.spotify.com/artist/2G7QgTep5IsJHGHm1hXygD

returns: `<img id="cidmgmt" src="https://pixel.spotify.com/v1/sync?nojs=1" style="display: none;" width="0" height="0" />` for both main image and images array,

instead of `<meta property="og:image" content="https://i.scdn.co/image/bad14a473f23b9ef78448336e6f1199e1de25e99">`

**Comment by LeonardoCardoso** [comment]
Fixed with the next version.

**Comment by haansplosion** [comment]
Hi there, tested with latest version and this still doesn't return go:image on Spotify links?
